### PR TITLE
Migrate to pytest-selenium and clean up some unused bits

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Comment by davehunt** [comment]
I'm seeing a couple of failures on an adhoc jobs.. hold off any reviews for now.

**Comment by davehunt** [comment]
Okay, I think this is ready for review. Please run the tests locally and report any issues.

Adhocs:
* [Sauce Labs (Windows)](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/affiliates.adhoc.pytest-selenium/9/)
* [Grid (Mac)](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/affiliates.adhoc.pytest-selenium/11/)
* [Grid (Windows)](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/affiliates.adhoc.pytest-selenium/12/)

**Comment by davehunt** [comment]
Pinging @mozilla/web-qa-sorcerers for review.

**Comment by justinpotts** [comment]
r+

**Comment by davehunt** [comment]
Thanks @justinpotts. Merged and updated Jenkins.

**Pull request merged**
