### PR TITLE
Updated Requirements.txt

### PR DESCRIPTION
**Pull request by tarun1992**

### CODE REVIEW

**Comment by m8ttyB** [comment]
Reviewing this now .. trying to understand why travis-ci is failing (https://travis-ci.org/mozilla/Affiliates-Tests/builds/62534597).

A future request @tarun1992, before doing work and submitting a pull request please create a new branch. Don't submit pull requests from your master branch. There are various ways to create a new working branch, my favorite is `git checkout -b pick_a_branch_name`

**Comment by stephendonner** [comment]
Might be due to execnet==1.0.9, when it's 1.1 in other upgraded projects' requirements.txt?  https://github.com/mozilla/mcom-tests/blob/master/requirements.txt#L9

**Comment by m8ttyB** [comment]
Spot on @stephendonner -- @tarun1992 please also bump the version number for `execnet` to `execnet==1.1`

**Comment by tarun1992** [comment]
@m8ttyB I am learning hot to create branch in git and all the stuff needed. In future, I will make sure that I make a pl not using master branch.

**Comment by davehunt** [comment]
Hmm.. execnet is not a direct dependency so I don't think it should even be in the requirements.txt file. For now I'm fine with either updating it to 1.1 or removing it altogether. Please update your commit message to more accurately reflect your change though. Something like 'Upgrade pytest dependencies'.

**Comment by davehunt** [comment]
Looks like this has been made obsolete by #127

**Pull request closed without merging**
