### PR TITLE
Update tests based on recent changes

### PR DESCRIPTION
**Pull request by davehunt**
Fixes for the following changes:
* Leaderboard and News pages have been removed
* Login denied for new users
* Modal splash page removed

The commits are intentionally separate. Here's a passing adhoc build: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/affiliates.adhoc/29/

Pinging @rbillings and @stephendonner for review due to @m8ttyB and @bobsilverberg being on PTO.

### CODE REVIEW

**Comment by stephendonner** [comment]
Very nice; this all makes sense to me - thanks for doing this!  Given dev/stage/prod are all identical, and all are also in PHX1, they'll be moved around the end of October by IT, so restoring (and augmenting) the coverage we had before makes sense to me - this will be useful as IT cuts the site over before its own December deadline/transition to Firefox Friends.

I'd like Rebecca to have a look too, but would be happy to merge to restore coverage, as well.  r+

**Comment by rbillings** [comment]
The changes look good to me, however I am getting errors running the tests: https://etherpad.mozilla.org/nJWQcfzAdd

As I'm out on PTO next week, you may need someone else to give the final thumbs up on this.

**Comment by davehunt** [comment]
The requirements.txt changed so I'm guessing @rbillings didn't run `pip install -Ur requirements.txt` to update the dependencies. Once done, you would also need to create a variables JSON file with the default user credentials. Perhaps now @m8ttyB should be back from PTO he can take a look.

I will confess that I'm not mad about my changes to `test_new_account_creation` as I've not used page objects. This is due to the current login method expecting a success and therefore timing out with a new user. Given this project is due to EOL soon, I decided not to spend too much time on the fix. I do think it's good to follow our best practices though, so I'll revisit this today.

**Comment by davehunt** [comment]
Okay, this is ready for review again and follows our best practices.

**Comment by m8ttyB** [comment]
r+ Nice bit of cleanup @davehunt! Awesome-fox-sox.

Merging

**Pull request merged**
